### ISSUE TITLE
Could not find SPIM

### ISSUE THREAD

**Issue by jacksonludwig** [hlissner/emacs-mips-mode#11]
Using C-c C-c gives the message "No such file or directory, spim."

Would you be able to tell me where spacemacs is looking for the spim files? The mips files are created in the tmp folder but the code is not actually interpreted.

**Comment by hlissner** [comment]
The interpreter is defined [on this line](https://github.com/hlissner/emacs-mips-mode/blob/master/mips-mode.el#L30). If it isn't an absolute path to the executable, it searches the `exec-path` variable in Emacs (see `C-h v exec-path` to see its value), which is constructed from your `PATH` environment variable when you start up Emacs.

So you have three options to change it:

1. `(setq mips-interpreter "/path/to/spim")`
2. `(add-to-list 'exec-path "/path/to")`
3. Add this to your shell config: `export PATH="/path/to:$PATH"`

None of this is particular to Spacemacs.

**Comment by jacksonludwig** [comment]
Firstly, thanks for the help.

I have put (setq mips-interpreter "C:/qtSpim/QtSpim.exe") in my init.el, however I am now getting a different error: 
"Wrong type argument, stringp, nil."

Would you be able to let me know what I'm doing wrong? If it's not clear enough already, I'm new to Emacs.

**Comment by hlissner** [comment]
> "Wrong type argument, stringp, nil."

This is a bug with the package. I will address it soon. That said, I'm not familiar with QtSpim and am uncertain if it will work for this purpose. Is it able to execute mips assembly on the command line? e.g. What happens when you do this from Emacs (assuming a `somefile.mips` exists):

`M-x shell-command RET C:\qtSpim\QtSpim.exe somefile.mips`
